//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoEntities1 : DbContext
    {
        public DemoEntities1()
            : base("name=DemoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPTDATA> DEPTDATAs { get; set; }
        public virtual DbSet<EMPDATA> EMPDATAs { get; set; }
        public virtual DbSet<Total> Totals { get; set; }
        public virtual DbSet<Total1> Total1 { get; set; }
    }
}
